final/config/routes.rb
Rails.application.routes.draw do

  root 'games#index'

  resources :games
  resources :users
  resources :game_sessions
  resources :collections
  resources :password_resets

  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

final/app/models/collection.rb
class Collection < ActiveRecord::Base
	belongs_to :game
	belongs_to :user
end

final/app/models/expansion.rb
class Expansion < ActiveRecord::Base
	belongs_to :game
end

final/app/models/game.rb
class Game < ActiveRecord::Base
	has_many :expansions
	has_many :collections
	has_many :users, :through => :collections
end

final/app/models/game_participant.rb
class GameParticipant < ActiveRecord::Base
end

final/app/models/game_session.rb
class GameSession < ActiveRecord::Base
	has_many :users
end

final/app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :collections
	has_many :games, :through => :collections

	def send_password_reset
		generate_token(:password_reset_token)
		self.password_reset_sent_at = Time.zone.now
		save!
		UserMailer.password_reset(self).deliver
	end

	def generate_token(column)
		begin
			self[column] = SecureRandom.urlsafe_base64
		end while User.exists?(column => self[column])
	end
end

final/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

final/app/controllers/collections_controller.rb
class CollectionsController < ApplicationController

  def create
  	collection = Collection.new
    temp = params[:collection]
  	collection.user_id = session[:user_id].to_i
  	collection.game_id = temp[:game_id]
  	collection.date_added =  Date.today
  	collection.rating = temp[:rating]
    collection.save
    redirect_to user_url(session[:user_id])
  end

  def show
  end

  def new
  	@collection = Collection.new
  end

  def edit
    @game = Game.find_by(id: params[:id])
  end

  def update
  end

  def destroy
  	collection = Collection.find_by(id: params[:id])
    if collection
      collection.delete
    end
    redirect_to user_url(session[:user_id])
  end
end

final/app/controllers/expansions_controller.rb
class ExpansionsController < ApplicationController

end

final/app/controllers/game_participants_controller.rb
class GameParticipantsController < ApplicationController

end

final/app/controllers/game_sessions_controller.rb
class GameSessionsController < ApplicationController
 def index
    @game_sessions = GameSession.all

    respond_to do |format|
      format.html do
        render 'index'
      end
      format.json do
        render json: @game_sessions
      end
      format.xml do
        render xml: @game_sessions
      end
    end

  end
end

final/app/controllers/games_controller.rb
class GamesController < ApplicationController
 def index
    @games = Game.all
    if params[:keyword].present?
      @games = @games.where("title LIKE ? OR year = ?", "%#{params[:keyword]}%", params[:keyword])
    end

    respond_to do |format|
      format.html do
        render 'index'
      end
      format.json do
        render json: @games
      end
      format.xml do
        render xml: @games
      end
    end

  end

  def create
  	game = Game.new
    temp = params[:game]
  	game.title = temp[:title]
  	game.cover_url = temp[:cover_url]
  	game.min_age = temp[:min_age]
  	game.year = temp[:year]
  	game.description = temp[:description]
  	game.min_playtime = temp[:min_playtime]
  	game.max_playtime = temp[:max_playtime]
  	game.min_players = temp[:min_players]
  	game.max_players = temp[:max_players]
    game.is_expansion = temp[:is_expansion]
    if game.is_expansion
      expansion = Expansion.new
      expansion.expansion_game_id = game.id
      expansion.base_id = temp[:base_id]
      game.base_id = temp[:base_id]
      expansion.save
    else
      game.base_id = nil
    end
    game.save
    
    redirect_to games_url
  end

  def show
    @game = Game.find_by(id: params[:id])
    if @game == nil
      redirect_to games_url
    end
    session["game_id"] = @game.id
  end

  def new
    @game = Game.new
  end

  def edit
    @game = Game.find_by(id: params[:id])
  end

  def update
    game = Game.find_by(id: params[:id])
    temp = params[:game]
    game.title = temp[:title]
  	game.cover_url = temp[:cover_url]
  	game.min_age = temp[:min_age]
  	game.year = temp[:year]
  	game.description = temp[:description]
  	game.min_playtime = temp[:min_playtime]
  	game.max_playtime = temp[:max_playtime]
  	game.min_players = temp[:min_players]
  	game.max_players = temp[:max_players]
    game.is_expansion = temp[:is_expansion]
    if game.is_expansion
      expansion = Expansion.new
      expansion.expansion_game_id = game.id
      expansion.base_id = temp[:base_id]
      game.base_id = temp[:base_id]
      expansion.save
    else
      game.base_id = nil
    end
    game.save
    redirect_to games_url(@game)
  end

  def destroy
  	game = Game.find_by(id: params[:id])
    if game
      game.delete
    end
    redirect_to games_url
  end
end

final/app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user
  		user.send_password_reset
  	end
  	redirect_to root_url, :notice => "Password reset sent in email."
  end

  def edit
  	@user = User.find_by_password_reset_token!(params[:id])
  end

  def update
  	@user = User.find_by_password_reset_token!(params[:id])
  	if @user.password_reset_sent_at < 2.hours.ago
  		redirect_to new_password_reset_path, :alert => "Password reset already expired, fool."
  	elsif @user.update_attributes(params.require(:user).permit(:password, :password_confirmation))
  		redirect_to root_url, :notice => "Password reset"
  	else 
  		render :edit
  	end
  end
end

final/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:email])
    if user
      if user.authenticate(params[:password])
        session["user_id"] = user.id
        redirect_to games_url
        return
      else
        # Email is ok, but password was wrong
      end
    else
      # Email is unknown
    end
    redirect_to games_url
  end

  def destroy
    reset_session
    redirect_to games_url
  end

end

final/app/controllers/user_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(id: params[:id])
    if !@user || (@user.id != session[:user_id].to_i)
      redirect_to root_url
    end
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    user = User.new
    user.name = params[:user][:name]
    user.email = params[:user][:email]
    user.password = params[:user][:password]
    user.save
    redirect_to movies_url
  end

  def destroy
    User.delete(params[:id])
    redirect_to users_url
  end
end

final/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(id: params[:id])
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    user.save
    redirect_to games_url
  end

  def destroy
    User.delete(params[:id])
    redirect_to users_url
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :salt, :encrypted_password)
  end
end

final/app/helpers/application_helper.rb
module ApplicationHelper
end

final/app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

final/app/views/collections/new.html.erb
<h1>Add New Game to Collection!</h1>

<%= form_for @collection do |form| %>

  <p><%= form.label :game_id, "Game" %>
  <br>
  <%= form.collection_select :game_id, Game.all.order('title'), :id, :title %></p>
  <p><%= form.label :rating %>
  <br>
  <%= form.text_field :rating %></p>
  <p><%= form.submit "Add game!" %></p>

<% end %>

final/app/views/game_sessions/_game_session.html.erb
<div>
  <p> <%= "Game Session #{game_session.id}" %> </p>
  <ul> <%= Game.find_by(id: game_session.game_id).title %> </ul>
  <ul> Played on: <%= game_session.played_on %>
  	<% GameParticipant.where(game_session_id: game_session.id).each do |part| %>
  		<ul> Player: <%= User.find(part.user_id).name %> </ul>
  		<ul> Score: <%= part.score %> </ul>
  		<ul> Did win? <%= part.did_win %> </ul>
  		<br>

  	<% end %>
  </ul>
</div>

final/app/views/game_sessions/index.html.erb
<%= render @game_sessions %>

final/app/views/games/_form.html.erb
<%= form_for @game do |form| %>

  <p><%= form.label :title %>
  <br>
  <%= form.text_field :title, size: 80, autofocus: true %></p>

  <p><%= form.label :year %>
  <br>
  <%= form.text_field :year %></p>

  <%= form.label :cover_url,  "Link to cover URL" %>
  <br>
  <%= form.text_field :cover_url, size: 80 %>

  <p><%= form.label :description %>
  <br>
  <%= form.text_area :description, rows: 4, cols: 80 %></p>

  <p><%= form.label :min_age, "Minimum player age" %>
  <br>
  <%= form.text_field :min_age %></p>

  <p><%= form.label :min_players, "Minimum number of players" %>
  <br>
  <%= form.text_field :min_players %></p>

  <p><%= form.label :max_players, "Maximum number of players" %>
  <br>
  <%= form.text_field :max_players %></p>

  <p><%= form.label :min_playtime, "Minimum playtime in minutes" %>
  <br>
  <%= form.text_field :min_playtime %></p>

  <p><%= form.label :max_playtime, "Maximum playtime in minutes" %>
  <br>
  <%= form.text_field :max_playtime %></p>

  <p><%= form.label :is_expansion, "Expansion?" %>
  <br>
  <%= form.check_box :is_expansion %></p>

  <p><%= form.label :base_id, "If expansion, what is the base game?" %>
  <br>
  <%= form.collection_select :base_id, Game.where(is_expansion: false).all.order('title'), :id, :title %></p>


  <%= form.submit %>
<% end %>

final/app/views/games/_game.html.erb
<% cover_url = game ? game.cover_url : 'add_new.png' %>
<% path = game ? game_path(game.id) : new_game_path %>

<div class="game-box">
  <%= link_to image_tag(cover_url), path %>
  <% if game %>
    <h3><%= link_to game.title, game_path(game.id) %></h3>
  <% end %>
</div>

final/app/views/games/edit.html.erb
<h2>Edit Game #<%= @game.id %></h2>

<%= render 'form' %>

final/app/views/games/index.html.erb
<div class="game-selections">
  <%= render 'game', game: nil %>
  <%= render @games %>
</div>

final/app/views/games/new.html.erb
<h2>Add A New Game!</h2>
<%= render 'form' %>

final/app/views/games/show.html.erb
<h1>
  <%= @game.title %>
  <small>
    <%= link_to "Edit This Game", edit_game_path(@game.id) %>
    <%= link_to "Delete This Game", game_path(@game.id), :method => :delete %>
  </small>
</h1>

<div class="details">

  <p><%= image_tag @game.cover_url, class: 'pull-right' %></p>

  <p><strong>Released:</strong> <%= @game.year %></p>
  <p><strong>Description:</strong> <%= @game.description %></p>
  <p><strong>Minimum player age: </strong> <%= @game.min_age %></p>
  <p><strong>Minimum # of players: </strong> <%= @game.min_players %></p>
  <p><strong>Maximum # of players: </strong> <%= @game.max_players %></p>
  <p><strong>Minimum playtime: </strong> <%= @game.min_playtime %></p>
  <p><strong>Maximum playtime: </strong> <%= @game.max_playtime %></p>
  <% if @game.is_expansion %>
    <% base_game = Game.find_by(id: @game.base_id) %>
    <p><strong> Base game: </strong> <%= link_to base_game.title, game_path(@game.base_id) %> </p>
  <% end %>

</div>

final/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TableTopNerd</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav>
    <ul>
      <li><%= link_to "Games", games_path %></li>
      <li><%= link_to "Game Sessions", game_sessions_path %></li>
      <li><%= link_to "Users", users_path %></li>
      <%= form_tag games_url, :method => :get do %>
        <%= text_field_tag :keyword, '', placeholder: 'Search by title...' %>
      <% end %>
    </ul>
    <ul class="nav-right">
      <% if session["user_id"].present? %>
        <% current_user = User.find_by(id: session["user_id"]) %>
        <li>Hello, <%= link_to current_user.name, user_path(current_user) %>!</li>
        <li><%= link_to "Sign Out", logout_path %></li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_path %></li>
        <li><%= link_to "Sign In", login_path %></li>
      <% end %>
    </ul>
  </nav>

  <div class="container">

    <%= yield %>

  </div>

</body>
</html>

final/app/views/password_resets/edit.html.erb
<h1> Reset The Password! </h1>

<%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
	<% if @user.errors.any? %>
		<div>
			<h2> Form is invalid </h2>
			<ul>
				<% for message in @user.errors.full_messages %>
				<li> <%= message %> </li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div>
		<%= f.label :password %>
		<%= f.password_field :password %>
	</div>

	<div>
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation %>
	</div>

	<div> <%= f.submit "Update Password" %> </div>
<% end %>

final/app/views/password_resets/new.html.erb
<h1>Reset Your Password</h1>

<%= form_tag password_resets_path, :method => :post do %>
<div>
	<%= label_tag :email %>
	<%= text_field_tag :email, params[:email] %>
</div>
<div>
	<%= submit_tag "Reset Password" %>
</div>
<% end %>

final/app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user_path(user.id) %></td>
        <td><%= user.email %></td>
        <td><%= link_to "Delete", user_path(user), method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

final/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>

  <p><%= f.label :name %><%= f.text_field :name, size: 40, autofocus: true, required: true %></p>
  <p><%= f.label :email %><%= f.text_field :email, size: 40, required: true %></p>
  <p><%= f.label :password %><%= f.password_field :password, size: 40, required: true %></p>
  <p><%= f.label :password_confirmation %><%= f.password_field :password_confirmation, size: 40, required: true %></p>
  <p><%= f.submit "Sign Me Up!" %></p>

<% end %>

final/app/views/users/show.html.erb
<h1>User Account</h1>

<p>Name: <%= @user.name %></p>
<p>Email: <%= @user.email %></p>

<h2>Collection</h2>
<% @user.collections.each do |collection| %>
	<% game = Game.find_by(id: collection.game_id)%>
	<p> <%= link_to game.title, game_path(game.id) %> </p> 
		<ul> Rating: <%= collection.rating %> </ul>
		<ul> Date Added: <%= collection.date_added %> </ul>
		<% if @user.id == session[:user_id].to_i %>
		  <ul> <%= link_to "Delete Game From Collection", collection_path(collection.id), :method => :delete %> </ul>
		<% end %>
<% end %>


<% if @user.id == session[:user_id].to_i %>
  <p> <%= link_to "Add Game To Collection", new_collection_path %> </p>
<% end %>